### ISSUE TITLE
Single chart type loading not working as expected

### ISSUE THREAD

**Issue by HappyOli** [mmathias01/google-charts#1]
when trying to load a specific chart type (ex. sankey), using a single string instead of an array of 1 string item doesn't works.

assuming type = 'sankey', 

if(!type.length) {   <-- should only validate type is not an array, since a string as a length property  
     type=[type]  <-- never gets hit
}

using ['sankey'] works as expected...

Thx for the library!

**Comment by mmathias01** [comment]
This is a good idea, I've used this approach several times in other projects and it would be a nice improvement here. I'll make this fix and put it up soon.

**Comment by mmathias01** [comment]
Resolved in version 1.0.0
