### ISSUE TITLE
With wicked_pdf gem google-charts lib don't work

### ISSUE THREAD

**Issue by valterbarros** [mmathias01/google-charts#10]
I don't know why but when I use the google-chart import, the graphs don't load in pdf using wicked_pdf gem

**Ruby version**
2.5.0
**Rails**
5.1.1
**Webpack**
3.1.0

**Comment by mmathias01** [comment]
I am not familiar with this GEM. What is it attempting to do?

**Comment by valterbarros** [comment]
Man, was a problem with wicked_pdf gem, you can close it :+1:

**Comment by mmathias01** [comment]
Glad its working for you now
