### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by QuentinMcCarthy** [mmathias01/google-charts#15]
I'm getting this error using google charts with node.js and React

I'm performing a request from a React server to the Node back-end server, and the Node server is routing the request and returning the GoogleCharts.js file, however I am getting the Unexpected token export error.

The error originates from line 44 in the googleCharts.js file:
`export let GoogleCharts = new googleCharts();`

Googling the error results in finding this solution:
`module.exports = googleCharts`
(https://stackoverflow.com/questions/51102034/unexpected-token-export-and-a-lot-more-errors-on-import-of-google-charts-in-mete)
However I am unable to implement this solution as it would require editing the googleCharts.js file in node_modules and the file would be overriden / would not be uploaded to the git repo.

Any chance this could be fixed?

**Comment by NoDirective** [comment]
I also have this problem

**Comment by mmathias01** [comment]
Try looking now. I updated the files and build significantly

**Comment by QuentinMcCarthy** [comment]
I cannot actually go in to attempt to reproduce this error to see if it's fixed or not as I am no longer working on this project nor using this package. Thanks for updating me, though!

**Comment by mmathias01** [comment]
No worries! Thanks for the update!
