### ISSUE TITLE
add locale

### ISSUE THREAD

**Issue by Fakkio** [mmathias01/google-charts#2]
Hi,

it would be nice if the package let the user to choose the locale.

TY,
Fabio.

**Comment by mmathias01** [comment]
I will look in to this! thanks!

**Comment by mmathias01** [comment]
Would this be something, you would consider submitting a PR for?

**Comment by Fakkio** [comment]
ok, i'll try!

**Comment by mmathias01** [comment]
I would say lets add a third parameter to ensure backwards compatibility. lets make the third parameter an object. Eventually we might want more parameters and this would be more future proof.

**Comment by Fakkio** [comment]
I'm on it. Two doubt:
1. If user wants to set the language (i call it language, not locale, to be consistent with Google chart property) but not the type, the call will be:
    ```
    GoogleCharts.load(callback, undefined, {language: "it"});
    ```
    very ugly. I can check if second parameter is an object and use that as third parameter, but i'd like to hear your opinion.
2. From doc:
    > As of version 45, you can call google.charts.load more than one time in order to load additional packages, but if you do so, you must provide the same version number and language setting each time.
we have to state this in doc too?
