### ISSUE TITLE
hjel

### ISSUE THREAD

**Issue by wslp12** [mmathias01/google-charts#4]
first sorry 
that subject is my bad 

I do not know why there is no load function

console.log 
![1](https://user-images.githubusercontent.com/26638889/36523980-913af4ba-17e7-11e8-8182-0d253e5a93b7.PNG)

component 
![2](https://user-images.githubusercontent.com/26638889/36523989-97f01e2a-17e7-11e8-8de5-5f48bdf5a790.PNG)

package.json
![3](https://user-images.githubusercontent.com/26638889/36523997-9e496376-17e7-11e8-8281-ad76c10c8913.PNG)

**Comment by mmathias01** [comment]
Is this still an issue? If so can you provide a repository for testing?

**Comment by wslp12** [comment]
nob this issue my misstake
