### ISSUE TITLE
IE11: Syntax error

### ISSUE THREAD

**Issue by samwx** [mmathias01/google-charts#8]
Syntax error caused by code above:
```
class googleCharts {
    [loadScript]() {
....
```

Using "normal" syntax (without [], and Symbol) worked, like 
```
class googleCharts {
    loadScript() {
....
```

Any reasons to use **Symbol** instead of class name?

**Comment by KoenDierckx** [comment]
I just ran into the same issue

**Comment by mmathias01** [comment]
using Symbol is designed to enforce the singularity of the object. Typically you would use this module in an environment that would get transpiled with babel or the like into something compatible with whatever your browser targets are. That being said I could look at providing a pre-transpiled version.

**Comment by KoenDierckx** [comment]
I'm using this within a Rails application, using webpack(er)
It works fine in Chrome, but not in Firefox and IE

**Comment by noelmccrory** [comment]
According to https://github.com/facebook/create-react-app/issues/1125 - "We don't recommend using libraries that don't precompile their code to ES5 but are supposed to be usable in ES5."

For now, I've updated my babel config to transpile the google-charts module. But have a pre-transpiled version would be great.

**Comment by mmathias01** [comment]
I am looking into a pre-transpiled version for 1.5.1

**Comment by mmathias01** [comment]
This should work now
